export const PALETTES = {
  "True Summer": [
    { name: "Cloud Whisper", hex: "#FAF9F9" },
    { name: "Alabaster Veil", hex: "#FBFAF5" },
    { name: "Linen Glow", hex: "#EDE6DB" },
    { name: "Moon Dust", hex: "#E7DED7" },
    { name: "Silver Raindrop", hex: "#B8BCC5" },
    { name: "Misty Steel", hex: "#949597" },
    { name: "Silver Fog", hex: "#A09C9D" },
    { name: "Stormy Harbor", hex: "#626669" },
    { name: "Cool Steel Grey", hex: "#685D64" },
    { name: "Driftwood Shadow", hex: "#786C6D" },
    { name: "Mulberry Mist", hex: "#685455" },
    { name: "Desert Rosewood", hex: "#BE9883" },
    { name: "Blush Shell", hex: "#E2C9C2" },
    { name: "Mauve Haze", hex: "#987C83" },
    { name: "Vintage Merlot", hex: "#725055" },
    { name: "Plum Shadow", hex: "#80565B" },
    { name: "Dusty Heather", hex: "#785C5D" },
    { name: "Cocoa Truffle", hex: "#6C5044" },
    { name: "Ballet Slipper", hex: "#E8B4C5" },
    { name: "Vintage Rose", hex: "#B3607F" },
    { name: "Cocoa Rose", hex: "#B07C7E" },
    { name: "Dusty Rose", hex: "#C08495" },
    { name: "Peony Blush", hex: "#C86C85" },
    { name: "Rosewood Bloom", hex: "#B05C6D" },
    { name: "Hibiscus Punch", hex: "#B84465" },
    { name: "Wild Raspberry", hex: "#B03C55" },
    { name: "Cranberry Velvet", hex: "#804455" },
    { name: "Rosewood Dust", hex: "#C53A4F" },
    { name: "Strawberry Blush", hex: "#BA2737" },
    { name: "Scarlet Flame", hex: "#B80F3E" },
    { name: "Hot Hibiscus", hex: "#D2386E" },
    { name: "Crimson Velvet", hex: "#852040" },
    { name: "Cherry Cordial", hex: "#9E1527" },
    { name: "Powdered Iris", hex: "#BCB9D4" },
    { name: "Petal Kiss", hex: "#D198C5" },
    { name: "Blush Veil", hex: "#B18FAA" },
    { name: "Orchid Dusk", hex: "#A76C98" },
    { name: "Heather Blush", hex: "#996B8B" },
    { name: "Misty Mauve", hex: "#9A8AAB" },
    { name: "Heather Grove", hex: "#817396" },
    { name: "Lavender Stone", hex: "#786C8D" },
    { name: "Lavender Twilight", hex: "#787495" },
    { name: "Violet Twilight", hex: "#60547D" },
    { name: "Plum Petal", hex: "#795483" },
    { name: "Mulberry Wine", hex: "#5A315B" },
    { name: "Berry Frost", hex: "#8F5076" },
    { name: "Seafoam Mist", hex: "#B7CDB8" },
    { name: "Sea Glass", hex: "#88ACAD" },
    { name: "Soft Glacier", hex: "#869BAE" },
    { name: "Cloudy Horizon", hex: "#788495" },
    { name: "Stormy Sky", hex: "#677789" },
    { name: "Blue Lagoon", hex: "#5E99BF" },
    { name: "Sky Drift", hex: "#78A4B4" },
    { name: "Coastal Breeze", hex: "#5E9EA0" },
    { name: "Ocean Deep", hex: "#487C8D" },
    { name: "Slate Harbor", hex: "#506C84" },
    { name: "Deep Marina", hex: "#405277" },
    { name: "Twilight Tide", hex: "#404C5D" },
    { name: "Midnight Sail", hex: "#1F305E" },
    { name: "Caribbean Surf", hex: "#0080B3" },
    { name: "Teel Wave", hex: "#006174" },
    { name: "Misty Periwinkle", hex: "#6F7EA6" },
    { name: "Bluebell Mist", hex: "#8084A5" },
    { name: "Indigo Whisper", hex: "#585C7D" },
    { name: "Moonlit Jetty", hex: "#585C6C" },
    { name: "Lemon Sorbet", hex: "#FFF4A5" }
  ],
  "Cool Summer": [
    { name: "Soft White", hex: "#F4F5F6" },
    { name: "Winter Cloud", hex: "#EEF3F8" },
    { name: "Icy Pearl", hex: "#DDE0E2" },
    { name: "Must Gray", hex: "#E0E0E0" },
    { name: "Cool Silver", hex: "#BDC5C9" },
    { name: "Dove Gray", hex: "#A7A9AC" },
    { name: "Deep Pewter", hex: "#5C5F64" },
    { name: "Blue Smoke", hex: "#5A5C66" },
    { name: "Charcoal Gray", hex: "#4B4F56" },
    { name: "Deep Graphite", hex: "#3C3F4A" },
    { name: "Charcoal Navy", hex: "#3B4658" },
    { name: "Slate Steel", hex: "#3B4A5A" },
    { name: "Ink Blue", hex: "#2E4C73" },
    { name: "Dusty Slate Blue", hex: "#4C618A" },
    { name: "Indigo Steel", hex: "#405495" },
    { name: "Blue Horizon", hex: "#4A77B1" },
    { name: "Cornflower Pop", hex: "#5D9DE6" },
    { name: "Bluebell Mist", hex: "#709EDC" },
    { name: "Dusty Periwinkle", hex: "#84A7DB" },
    { name: "Soft Denim", hex: "#7CA7D9" },
    { name: "Icy Cornflower", hex: "#88B4D5" },
    { name: "Powder Blue", hex: "#B4D7EA" },
    { name: "Sky Tint", hex: "#89CFF0" },
    { name: "Cool Pool", hex: "#58BCDD" },
    { name: "Vivid Azure", hex: "#08ACDD" },
    { name: "Cobalt Coast", hex: "#106CA5" },
    { name: "Shadowed Spruce", hex: "#2E5C50" },
    { name: "Whisper Jade", hex: "#3F6E61" },
    { name: "Powdered Emerald", hex: "#3E8C76" },
    { name: "Deep Seafom Drift", hex: "#4B877C" },
    { name: "Sea-Glass Emerald", hex: "#3A9A85" },
    { name: "Tropical Jade", hex: "#3CAFA8" },
    { name: "Deep Teal Surf", hex: "#08A4A5" },
    { name: "Splash Teal", hex: "#3CB3BD" },
    { name: "Cool Bay", hex: "#60BCB5" },
    { name: "Misty Turquoise", hex: "#5FA8A0" },
    { name: "Icy Mint", hex: "#BAE6DD" },
    { name: "Glacier Wash", hex: "#C8E4E5" },
    { name: "Winter Mist", hex: "#E6F1F2" },
    { name: "Powdered Periwinkle", hex: "#B5BFD1" },
    { name: "Clouded Blue Ice", hex: "#C8D4E5" },
    { name: "Muted Orchid Mist", hex: "#D2BEE2" },
    { name: "Soft Lavender Grey", hex: "#D8CBEF" },
    { name: "Cornflower Indigo", hex: "#6A6ECF" },
    { name: "Dusty Iris", hex: "#7874AD" },
    { name: "Plum Smoke", hex: "#704C8D" },
    { name: "Grape Bark", hex: "#783C85" },
    { name: "Deep Berry Rose", hex: "#A83C85" },
    { name: "Frosted Plum", hex: "#8E4585" },
    { name: "Heathered Mauve", hex: "#B77EC3" },
    { name: "Orchid Pop", hex: "#A654B8" },
    { name: "Mulberry Rose", hex: "#C084AD" },
    { name: "Lemon Popsicle", hex: "#ECE26A" },
    { name: "Rosie Fuschia", hex: "#C72C86" },
    { name: "Fuchsia Flame", hex: "#E62C65" },
    { name: "Cardinal Red", hex: "#C41E3A" },
    { name: "Pink Punch", hex: "#E7487D" },
    { name: "Raspberry Bubblegum", hex: "#E75480" },
    { name: "Honeysuckle Rose", hex: "#D65076" },
    { name: "Strawberry Cream", hex: "#F45B7A" },
    { name: "Soft Tulip", hex: "#EC7192" },
    { name: "Soft Magenta Rose", hex: "#E06C9F" },
    { name: "Sweetpea Pink", hex: "#C86FAE" },
    { name: "Cool Bubblegum", hex: "#FFC1CC" },
    { name: "Petal Ice", hex: "#FFDCDB" },
    { name: "Cranberry Plum", hex: "#9B3B57" }
  ]
};
