export const PALETTES = {
  "True Summer": [
    { name: "Powder Blue", hex: "#B0C4DE" },
    { name: "Dusty Blue", hex: "#7393B3" },
    { name: "Steel Blue", hex: "#4F81A0" },
    { name: "Slate Blue", hex: "#6B7FA3" },
    { name: "Periwinkle", hex: "#8896C8" },
    { name: "Lavender Blue", hex: "#9BA8D0" },
    { name: "Muted Violet", hex: "#8A7FB5" },
    { name: "Dusty Purple", hex: "#9B8DB5" },
    { name: "Mauve", hex: "#B09BB5" },
    { name: "Soft Plum", hex: "#A08090" },
    { name: "Rose Taupe", hex: "#B08890" },
    { name: "Dusty Rose", hex: "#C4A0A8" },
    { name: "Antique Pink", hex: "#D4AEBA" },
    { name: "Muted Pink", hex: "#D4A8B8" },
    { name: "Soft Fuchsia", hex: "#C090B0" },
    { name: "Orchid", hex: "#B87898" },
    { name: "Muted Magenta", hex: "#B07890" },
    { name: "Raspberry", hex: "#A05878" },
    { name: "Deep Rose", hex: "#984068" },
    { name: "Burgundy", hex: "#803050" },
    { name: "Wine", hex: "#6E2848" },
    { name: "Dark Berry", hex: "#5C2040" },
    { name: "Plum", hex: "#704870" },
    { name: "Deep Plum", hex: "#5A3860" },
    { name: "Amethyst", hex: "#786898" },
    { name: "Grape", hex: "#684878" },
    { name: "Eggplant", hex: "#4A2850" },
    { name: "Soft Teal", hex: "#7AA8A8" },
    { name: "Sea Glass", hex: "#90B8B8" },
    { name: "Dusty Teal", hex: "#6898A0" },
    { name: "Muted Seafoam", hex: "#88B0A8" },
    { name: "Sage", hex: "#98A898" },
    { name: "Dusty Green", hex: "#88A090" },
    { name: "Eucalyptus", hex: "#7A9890" },
    { name: "Muted Jade", hex: "#78A898" },
    { name: "Slate Green", hex: "#708888" },
    { name: "Stone Green", hex: "#809090" },
    { name: "Blue Grey", hex: "#8898A8" },
    { name: "Cool Grey", hex: "#9098A8" },
    { name: "Silver Blue", hex: "#A0AABB" },
    { name: "Mist", hex: "#B8C0CC" },
    { name: "Dove Grey", hex: "#A8A8B0" },
    { name: "Ash Grey", hex: "#989898" },
    { name: "Stone", hex: "#909098" },
    { name: "Taupe Grey", hex: "#A09890" },
    { name: "Greige", hex: "#B0A898" },
    { name: "Warm Grey", hex: "#A89888" },
    { name: "Cocoa", hex: "#907868" },
    { name: "Mushroom", hex: "#A09080" },
    { name: "Sand", hex: "#C0B098" },
    { name: "Buff", hex: "#C8B890" },
    { name: "Wheat", hex: "#C8B898" },
    { name: "Pale Gold", hex: "#C8B880" },
    { name: "Soft Camel", hex: "#C0A880" },
    { name: "Muted Gold", hex: "#B8A070" },
    { name: "Khaki", hex: "#A89868" },
    { name: "Soft Ivory", hex: "#E8E0D0" },
    { name: "Cream", hex: "#E0D8C8" },
    { name: "Linen", hex: "#D8D0C0" },
    { name: "Pearl", hex: "#E0DCE0" },
    { name: "Snow", hex: "#E8E8EC" },
    { name: "Silver", hex: "#C0C0C8" },
    { name: "Navy", hex: "#404870" },
    { name: "Midnight Blue", hex: "#303858" },
    { name: "Charcoal Blue", hex: "#384050" }
  ],
  "Cool Summer": [
    { name: "Soft White", hex: "#F4F5F6" },
    { name: "Winter Cloud", hex: "#EEF3F8" },
    { name: "Icy Pearl", hex: "#DDE0E2" },
    { name: "Must Gray", hex: "#E0E0E0" },
    { name: "Cool Silver", hex: "#BDC5C9" },
    { name: "Dove Gray", hex: "#A7A9AC" },
    { name: "Deep Pewter", hex: "#5C5F64" },
    { name: "Blue Smoke", hex: "#5A5C66" },
    { name: "Charcoal Gray", hex: "#4B4F56" },
    { name: "Deep Graphite", hex: "#3C3F4A" },
    { name: "Charcoal Navy", hex: "#3B4658" },
    { name: "Slate Steel", hex: "#3B4A5A" },
    { name: "Ink Blue", hex: "#2E4C73" },
    { name: "Dusty Slate Blue", hex: "#4C618A" },
    { name: "Indigo Steel", hex: "#405495" },
    { name: "Blue Horizon", hex: "#4A77B1" },
    { name: "Cornflower Pop", hex: "#5D9DE6" },
    { name: "Bluebell Mist", hex: "#709EDC" },
    { name: "Dusty Periwinkle", hex: "#84A7DB" },
    { name: "Soft Denim", hex: "#7CA7D9" },
    { name: "Icy Cornflower", hex: "#88B4D5" },
    { name: "Powder Blue", hex: "#B4D7EA" },
    { name: "Sky Tint", hex: "#89CFF0" },
    { name: "Cool Pool", hex: "#58BCDD" },
    { name: "Vivid Azure", hex: "#08ACDD" },
    { name: "Cobalt Coast", hex: "#106CA5" },
    { name: "Shadowed Spruce", hex: "#2E5C50" },
    { name: "Whisper Jade", hex: "#3F6E61" },
    { name: "Powdered Emerald", hex: "#3E8C76" },
    { name: "Deep Seafom Drift", hex: "#4B877C" },
    { name: "Sea-Glass Emerald", hex: "#3A9A85" },
    { name: "Tropical Jade", hex: "#3CAFA8" },
    { name: "Deep Teal Surf", hex: "#08A4A5" },
    { name: "Splash Teal", hex: "#3CB3BD" },
    { name: "Cool Bay", hex: "#60BCB5" },
    { name: "Misty Turquoise", hex: "#5FA8A0" },
    { name: "Icy Mint", hex: "#BAE6DD" },
    { name: "Glacier Wash", hex: "#C8E4E5" },
    { name: "Winter Mist", hex: "#E6F1F2" },
    { name: "Powdered Periwinkle", hex: "#B5BFD1" },
    { name: "Clouded Blue Ice", hex: "#C8D4E5" },
    { name: "Muted Orchid Mist", hex: "#D2BEE2" },
    { name: "Soft Lavender Grey", hex: "#D8CBEF" },
    { name: "Cornflower Indigo", hex: "#6A6ECF" },
    { name: "Dusty Iris", hex: "#7874AD" },
    { name: "Plum Smoke", hex: "#704C8D" },
    { name: "Grape Bark", hex: "#783C85" },
    { name: "Deep Berry Rose", hex: "#A83C85" },
    { name: "Frosted Plum", hex: "#8E4585" },
    { name: "Heathered Mauve", hex: "#B77EC3" },
    { name: "Orchid Pop", hex: "#A654B8" },
    { name: "Mulberry Rose", hex: "#C084AD" },
    { name: "Lemon Popsicle", hex: "#ECE26A" },
    { name: "Rosie Fuschia", hex: "#C72C86" },
    { name: "Fuchsia Flame", hex: "#E62C65" },
    { name: "Cardinal Red", hex: "#C41E3A" },
    { name: "Pink Punch", hex: "#E7487D" },
    { name: "Raspberry Bubblegum", hex: "#E75480" },
    { name: "Honeysuckle Rose", hex: "#D65076" },
    { name: "Strawberry Cream", hex: "#F45B7A" },
    { name: "Soft Tulip", hex: "#EC7192" },
    { name: "Soft Magenta Rose", hex: "#E06C9F" },
    { name: "Sweetpea Pink", hex: "#C86FAE" },
    { name: "Cool Bubblegum", hex: "#FFC1CC" },
    { name: "Petal Ice", hex: "#FFDCDB" },
    { name: "Cranberry Plum", hex: "#9B3B57" }
  ]
};
