export const PALETTES = {
  "True Summer": [
    { name: "Powder Blue", hex: "#B0C4DE" },
    { name: "Dusty Blue", hex: "#7393B3" },
    { name: "Steel Blue", hex: "#4F81A0" },
    { name: "Slate Blue", hex: "#6B7FA3" },
    { name: "Periwinkle", hex: "#8896C8" },
    { name: "Lavender Blue", hex: "#9BA8D0" },
    { name: "Muted Violet", hex: "#8A7FB5" },
    { name: "Dusty Purple", hex: "#9B8DB5" },
    { name: "Mauve", hex: "#B09BB5" },
    { name: "Soft Plum", hex: "#A08090" },
    { name: "Rose Taupe", hex: "#B08890" },
    { name: "Dusty Rose", hex: "#C4A0A8" },
    { name: "Antique Pink", hex: "#D4AEBA" },
    { name: "Muted Pink", hex: "#D4A8B8" },
    { name: "Soft Fuchsia", hex: "#C090B0" },
    { name: "Orchid", hex: "#B87898" },
    { name: "Muted Magenta", hex: "#B07890" },
    { name: "Raspberry", hex: "#A05878" },
    { name: "Deep Rose", hex: "#984068" },
    { name: "Burgundy", hex: "#803050" },
    { name: "Wine", hex: "#6E2848" },
    { name: "Dark Berry", hex: "#5C2040" },
    { name: "Plum", hex: "#704870" },
    { name: "Deep Plum", hex: "#5A3860" },
    { name: "Amethyst", hex: "#786898" },
    { name: "Grape", hex: "#684878" },
    { name: "Eggplant", hex: "#4A2850" },
    { name: "Soft Teal", hex: "#7AA8A8" },
    { name: "Sea Glass", hex: "#90B8B8" },
    { name: "Dusty Teal", hex: "#6898A0" },
    { name: "Muted Seafoam", hex: "#88B0A8" },
    { name: "Sage", hex: "#98A898" },
    { name: "Dusty Green", hex: "#88A090" },
    { name: "Eucalyptus", hex: "#7A9890" },
    { name: "Muted Jade", hex: "#78A898" },
    { name: "Slate Green", hex: "#708888" },
    { name: "Stone Green", hex: "#809090" },
    { name: "Blue Grey", hex: "#8898A8" },
    { name: "Cool Grey", hex: "#9098A8" },
    { name: "Silver Blue", hex: "#A0AABB" },
    { name: "Mist", hex: "#B8C0CC" },
    { name: "Dove Grey", hex: "#A8A8B0" },
    { name: "Ash Grey", hex: "#989898" },
    { name: "Stone", hex: "#909098" },
    { name: "Taupe Grey", hex: "#A09890" },
    { name: "Greige", hex: "#B0A898" },
    { name: "Warm Grey", hex: "#A89888" },
    { name: "Cocoa", hex: "#907868" },
    { name: "Mushroom", hex: "#A09080" },
    { name: "Sand", hex: "#C0B098" },
    { name: "Buff", hex: "#C8B890" },
    { name: "Wheat", hex: "#C8B898" },
    { name: "Pale Gold", hex: "#C8B880" },
    { name: "Soft Camel", hex: "#C0A880" },
    { name: "Muted Gold", hex: "#B8A070" },
    { name: "Khaki", hex: "#A89868" },
    { name: "Soft Ivory", hex: "#E8E0D0" },
    { name: "Cream", hex: "#E0D8C8" },
    { name: "Linen", hex: "#D8D0C0" },
    { name: "Pearl", hex: "#E0DCE0" },
    { name: "Snow", hex: "#E8E8EC" },
    { name: "Silver", hex: "#C0C0C8" },
    { name: "Navy", hex: "#404870" },
    { name: "Midnight Blue", hex: "#303858" },
    { name: "Charcoal Blue", hex: "#384050" }
  ]
};
